# Generated by Django 4.2.1 on 2023-05-12 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='update_by',
            new_name='updated_by',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='create_by',
        ),
        migrations.AddField(
            model_name='reply',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
